project:
  type: website

website:
  title: "LG 25 26"
  navbar:
    background: primary
    search: true
    left:
      - text: "Ilias"
        href: index.qmd
      - Linksammlung.qmd


format:
  html:
    theme:
      - default
    css: styles.css
    