project:
  type: website
  resources:
    - thumbnails/**


website:
  title: "LG 25 26"
  navbar:
    background: primary
    search: true
    left:
      - text: "Ilias"
        href: index.qmd
      - Linksammlung.qmd
      - slides.qmd


format:
  
  
  html:
    theme:
      - default
    style: style/styles.css
  revealjs:
    style: style/manuscript.scss
    lang: en
    csl: style/apa.csl
    date-format: "DD.MM.YYYY  [um]   HH:mm"
    theme: [default,style/manuscript.scss]   # "black" base theme helps with dark mode
    center: false
    transition: none
    slide-number: false
    controls: false
    progress: false
    menu: false
    bibliography: bibliography/richard.bib
    mermaid:
      theme: dark
    scrollable: true
    linkcolor: "#27E4F5"


    
    
    