project:
  type: website

website:
  title: "LG 25 26"
  navbar:
    background: primary
    search: true
    left:
      - text: "Ilias"
        href: index.qmd
      - Linksammlung.qmd


format:
  html:
    theme:
      - darkly 
      - brand
    css: styles.css
    toc: true
    
  phheidelberg-revealjs:
    scrollable: true
    hide-inactive-cursor: true
    title-slide-attributes: 
      data-background-image: "images/logo cc-by-sa.svg"
      data-background-size: 12%
      data-background-position: 94% 99%
    footer: "[PH Heidelberg,](https://www.ph-heidelberg.de/mathematik/personen/promovierende/richard-conrardy/)  Richard Conrardy"

